// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi

import (
	"context"
	"net/http"
)



// ExecutionAPIRouter defines the required methods for binding the api requests to a responses for the ExecutionAPI
// The ExecutionAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ExecutionAPIServicer to perform the required actions, then write the service results to the http response.
type ExecutionAPIRouter interface { 
	GetQueries(http.ResponseWriter, *http.Request)
	GetQueryById(http.ResponseWriter, *http.Request)
	SubmitQuery(http.ResponseWriter, *http.Request)
	GetQueryResult(http.ResponseWriter, *http.Request)
	GetQueryError(http.ResponseWriter, *http.Request)
}
// MetadataAPIRouter defines the required methods for binding the api requests to a responses for the MetadataAPI
// The MetadataAPIRouter implementation should parse necessary information from the http request,
// pass the data to a MetadataAPIServicer to perform the required actions, then write the service results to the http response.
type MetadataAPIRouter interface { 
	GetSystemInfo(http.ResponseWriter, *http.Request)
}
// Proj3APIRouter defines the required methods for binding the api requests to a responses for the Proj3API
// The Proj3APIRouter implementation should parse necessary information from the http request,
// pass the data to a Proj3APIServicer to perform the required actions, then write the service results to the http response.
type Proj3APIRouter interface { 
	GetTables(http.ResponseWriter, *http.Request)
	GetTableById(http.ResponseWriter, *http.Request)
	DeleteTable(http.ResponseWriter, *http.Request)
	CreateTable(http.ResponseWriter, *http.Request)
	GetQueries(http.ResponseWriter, *http.Request)
	GetQueryById(http.ResponseWriter, *http.Request)
	SubmitQuery(http.ResponseWriter, *http.Request)
	GetQueryResult(http.ResponseWriter, *http.Request)
	GetQueryError(http.ResponseWriter, *http.Request)
	GetSystemInfo(http.ResponseWriter, *http.Request)
}
// Proj4APIRouter defines the required methods for binding the api requests to a responses for the Proj4API
// The Proj4APIRouter implementation should parse necessary information from the http request,
// pass the data to a Proj4APIServicer to perform the required actions, then write the service results to the http response.
type Proj4APIRouter interface { 
	GetQueries(http.ResponseWriter, *http.Request)
}
// SchemaAPIRouter defines the required methods for binding the api requests to a responses for the SchemaAPI
// The SchemaAPIRouter implementation should parse necessary information from the http request,
// pass the data to a SchemaAPIServicer to perform the required actions, then write the service results to the http response.
type SchemaAPIRouter interface { 
	GetTables(http.ResponseWriter, *http.Request)
	GetTableById(http.ResponseWriter, *http.Request)
	DeleteTable(http.ResponseWriter, *http.Request)
	CreateTable(http.ResponseWriter, *http.Request)
}


// ExecutionAPIServicer defines the api actions for the ExecutionAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ExecutionAPIServicer interface { 
	GetQueries(context.Context) (ImplResponse, error)
	GetQueryById(context.Context, string) (ImplResponse, error)
	SubmitQuery(context.Context, ExecuteQueryRequest) (ImplResponse, error)
	GetQueryResult(context.Context, string, GetQueryResultRequest) (ImplResponse, error)
	GetQueryError(context.Context, string) (ImplResponse, error)
}


// MetadataAPIServicer defines the api actions for the MetadataAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type MetadataAPIServicer interface { 
	GetSystemInfo(context.Context) (ImplResponse, error)
}


// Proj3APIServicer defines the api actions for the Proj3API service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type Proj3APIServicer interface { 
	GetTables(context.Context) (ImplResponse, error)
	GetTableById(context.Context, string) (ImplResponse, error)
	DeleteTable(context.Context, string) (ImplResponse, error)
	CreateTable(context.Context, TableSchema) (ImplResponse, error)
	GetQueries(context.Context) (ImplResponse, error)
	GetQueryById(context.Context, string) (ImplResponse, error)
	SubmitQuery(context.Context, ExecuteQueryRequest) (ImplResponse, error)
	GetQueryResult(context.Context, string, GetQueryResultRequest) (ImplResponse, error)
	GetQueryError(context.Context, string) (ImplResponse, error)
	GetSystemInfo(context.Context) (ImplResponse, error)
}


// Proj4APIServicer defines the api actions for the Proj4API service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type Proj4APIServicer interface { 
	GetQueries(context.Context) (ImplResponse, error)
}


// SchemaAPIServicer defines the api actions for the SchemaAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SchemaAPIServicer interface { 
	GetTables(context.Context) (ImplResponse, error)
	GetTableById(context.Context, string) (ImplResponse, error)
	DeleteTable(context.Context, string) (ImplResponse, error)
	CreateTable(context.Context, TableSchema) (ImplResponse, error)
}
