// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// SchemaAPIService is a service that implements the logic for the SchemaAPIServicer
// This service should implement the business logic for every endpoint for the SchemaAPI API.
// Include any external packages or services that will be required by this service.
type SchemaAPIService struct {
}

// NewSchemaAPIService creates a default api service
func NewSchemaAPIService() *SchemaAPIService {
	return &SchemaAPIService{}
}

// GetTables - Get list of tables with their accompanying IDs. Use those IDs to get details by calling /table endpoint.
func (s *SchemaAPIService) GetTables(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetTables with the required logic for this service method.
	// Add api_schema_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []ShallowTable{}) or use other options such as http.Ok ...
	// return Response(200, []ShallowTable{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTables method not implemented")
}

// GetTableById - Get detailed description of selected table
func (s *SchemaAPIService) GetTableById(ctx context.Context, tableId string) (ImplResponse, error) {
	// TODO - update GetTableById with the required logic for this service method.
	// Add api_schema_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TableSchema{}) or use other options such as http.Ok ...
	// return Response(200, TableSchema{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTableById method not implemented")
}

// DeleteTable - Delete selected table from database
func (s *SchemaAPIService) DeleteTable(ctx context.Context, tableId string) (ImplResponse, error) {
	// TODO - update DeleteTable with the required logic for this service method.
	// Add api_schema_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteTable method not implemented")
}

// CreateTable - Create new table in database
func (s *SchemaAPIService) CreateTable(ctx context.Context, tableSchema TableSchema) (ImplResponse, error) {
	// TODO - update CreateTable with the required logic for this service method.
	// Add api_schema_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, string{}) or use other options such as http.Ok ...
	// return Response(200, string{}), nil

	// TODO: Uncomment the next line to return response Response(400, MultipleProblemsError{}) or use other options such as http.Ok ...
	// return Response(400, MultipleProblemsError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateTable method not implemented")
}
