// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// SchemaAPIController binds http requests to an api service and writes the service results to the http response
type SchemaAPIController struct {
	service SchemaAPIServicer
	errorHandler ErrorHandler
}

// SchemaAPIOption for how the controller is set up.
type SchemaAPIOption func(*SchemaAPIController)

// WithSchemaAPIErrorHandler inject ErrorHandler into controller
func WithSchemaAPIErrorHandler(h ErrorHandler) SchemaAPIOption {
	return func(c *SchemaAPIController) {
		c.errorHandler = h
	}
}

// NewSchemaAPIController creates a default api controller
func NewSchemaAPIController(s SchemaAPIServicer, opts ...SchemaAPIOption) *SchemaAPIController {
	controller := &SchemaAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the SchemaAPIController
func (c *SchemaAPIController) Routes() Routes {
	return Routes{
		"GetTables": Route{
			"GetTables",
			strings.ToUpper("Get"),
			"/tables",
			c.GetTables,
		},
		"GetTableById": Route{
			"GetTableById",
			strings.ToUpper("Get"),
			"/table/{tableId}",
			c.GetTableById,
		},
		"DeleteTable": Route{
			"DeleteTable",
			strings.ToUpper("Delete"),
			"/table/{tableId}",
			c.DeleteTable,
		},
		"CreateTable": Route{
			"CreateTable",
			strings.ToUpper("Put"),
			"/table",
			c.CreateTable,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the SchemaAPIController
func (c *SchemaAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetTables",
			strings.ToUpper("Get"),
			"/tables",
			c.GetTables,
		},
		Route{
			"GetTableById",
			strings.ToUpper("Get"),
			"/table/{tableId}",
			c.GetTableById,
		},
		Route{
			"DeleteTable",
			strings.ToUpper("Delete"),
			"/table/{tableId}",
			c.DeleteTable,
		},
		Route{
			"CreateTable",
			strings.ToUpper("Put"),
			"/table",
			c.CreateTable,
		},
	}
}



// GetTables - Get list of tables with their accompanying IDs. Use those IDs to get details by calling /table endpoint.
func (c *SchemaAPIController) GetTables(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetTables(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetTableById - Get detailed description of selected table
func (c *SchemaAPIController) GetTableById(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	tableIdParam := params["tableId"]
	if tableIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"tableId"}, nil)
		return
	}
	result, err := c.service.GetTableById(r.Context(), tableIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteTable - Delete selected table from database
func (c *SchemaAPIController) DeleteTable(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	tableIdParam := params["tableId"]
	if tableIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"tableId"}, nil)
		return
	}
	result, err := c.service.DeleteTable(r.Context(), tableIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// CreateTable - Create new table in database
func (c *SchemaAPIController) CreateTable(w http.ResponseWriter, r *http.Request) {
	var tableSchemaParam TableSchema
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&tableSchemaParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTableSchemaRequired(tableSchemaParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTableSchemaConstraints(tableSchemaParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateTable(r.Context(), tableSchemaParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
