// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




// Query - Description of a query in the system
type Query struct {

	// ID of selected Query (I propose UUID, but it is under your own discretion)
	QueryId string `json:"queryId"`

	Status QueryStatus `json:"status"`

	// Whether result of this query is already available
	IsResultAvailable bool `json:"isResultAvailable,omitempty"`

	QueryDefinition QueryQueryDefinition `json:"queryDefinition,omitempty"`
}

// AssertQueryRequired checks if the required fields are not zero-ed
func AssertQueryRequired(obj Query) error {
	elements := map[string]interface{}{
		"queryId": obj.QueryId,
		"status": obj.Status,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertQueryQueryDefinitionRequired(obj.QueryDefinition); err != nil {
		return err
	}
	return nil
}

// AssertQueryConstraints checks if the values respects the defined constraints
func AssertQueryConstraints(obj Query) error {
	if err := AssertQueryQueryDefinitionConstraints(obj.QueryDefinition); err != nil {
		return err
	}
	return nil
}
