// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi


import (
	"fmt"
)


// QueryStatus : Enum describing possible query statuses
type QueryStatus string

// List of QueryStatus
const (
	CREATED QueryStatus = "CREATED"
	PLANNING QueryStatus = "PLANNING"
	RUNNING QueryStatus = "RUNNING"
	COMPLETED QueryStatus = "COMPLETED"
	FAILED QueryStatus = "FAILED"
)

// AllowedQueryStatusEnumValues is all the allowed values of QueryStatus enum
var AllowedQueryStatusEnumValues = []QueryStatus{
	"CREATED",
	"PLANNING",
	"RUNNING",
	"COMPLETED",
	"FAILED",
}

// validQueryStatusEnumValue provides a map of QueryStatuss for fast verification of use input
var validQueryStatusEnumValues = map[QueryStatus]struct{}{
	"CREATED": {},
	"PLANNING": {},
	"RUNNING": {},
	"COMPLETED": {},
	"FAILED": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v QueryStatus) IsValid() bool {
	_, ok := validQueryStatusEnumValues[v]
	return ok
}

// NewQueryStatusFromValue returns a pointer to a valid QueryStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewQueryStatusFromValue(v string) (QueryStatus, error) {
	ev := QueryStatus(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for QueryStatus: valid values are %v", v, AllowedQueryStatusEnumValues)
}



// AssertQueryStatusRequired checks if the required fields are not zero-ed
func AssertQueryStatusRequired(obj QueryStatus) error {
	return nil
}

// AssertQueryStatusConstraints checks if the values respects the defined constraints
func AssertQueryStatusConstraints(obj QueryStatus) error {
	return nil
}
