// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




// TableSchema - Description of the table in the database
type TableSchema struct {

	Name string `json:"name"`

	Columns []Column `json:"columns"`
}

// AssertTableSchemaRequired checks if the required fields are not zero-ed
func AssertTableSchemaRequired(obj TableSchema) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"columns": obj.Columns,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Columns {
		if err := AssertColumnRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTableSchemaConstraints checks if the values respects the defined constraints
func AssertTableSchemaConstraints(obj TableSchema) error {
	for _, el := range obj.Columns {
		if err := AssertColumnConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
