// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




type MultipleProblemsErrorProblemsInner struct {

	// Description of particular problem
	Error string `json:"error"`

	// Optional context for user (for e.g. which column caused problem). It can be helpful for troubleshooting.
	Context string `json:"context,omitempty"`
}

// AssertMultipleProblemsErrorProblemsInnerRequired checks if the required fields are not zero-ed
func AssertMultipleProblemsErrorProblemsInnerRequired(obj MultipleProblemsErrorProblemsInner) error {
	elements := map[string]interface{}{
		"error": obj.Error,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMultipleProblemsErrorProblemsInnerConstraints checks if the values respects the defined constraints
func AssertMultipleProblemsErrorProblemsInnerConstraints(obj MultipleProblemsErrorProblemsInner) error {
	return nil
}
