// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




// CopyQuery - Description of the COPY query from CSV file. Server will read the file and insert all data into selected table. When number of columns in source and target doesn't match, user have to use \"destinationColumns\" property to specify which columns data should be inserted into.
type CopyQuery struct {

	// Path to source CSV file (filepath in perspective of running server! NOT client)
	SourceFilepath string `json:"sourceFilepath"`

	DestinationTableName string `json:"destinationTableName"`

	// List of columns to copy data into. It creates a map from source columns to destination columns. Assumes that data in source file is in the same order as in this list.
	DestinationColumns []string `json:"destinationColumns,omitempty"`

	// Whether CSV file contains header row
	DoesCsvContainHeader bool `json:"doesCsvContainHeader,omitempty"`
}

// AssertCopyQueryRequired checks if the required fields are not zero-ed
func AssertCopyQueryRequired(obj CopyQuery) error {
	elements := map[string]interface{}{
		"sourceFilepath": obj.SourceFilepath,
		"destinationTableName": obj.DestinationTableName,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCopyQueryConstraints checks if the values respects the defined constraints
func AssertCopyQueryConstraints(obj CopyQuery) error {
	return nil
}
