// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




// ShallowTable - Description of a shallow representation of a table (e.g. without detailed column information)
type ShallowTable struct {

	// ID of selected Table (I propose UUID, but it is under your own discretion)
	TableId string `json:"tableId,omitempty"`

	Name string `json:"name"`
}

// AssertShallowTableRequired checks if the required fields are not zero-ed
func AssertShallowTableRequired(obj ShallowTable) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertShallowTableConstraints checks if the values respects the defined constraints
func AssertShallowTableConstraints(obj ShallowTable) error {
	return nil
}
