// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




// SelectQuery - Description of a select query (extension in project no 4)
type SelectQuery struct {

	TableName string `json:"tableName,omitempty"`
}

// AssertSelectQueryRequired checks if the required fields are not zero-ed
func AssertSelectQueryRequired(obj SelectQuery) error {
	return nil
}

// AssertSelectQueryConstraints checks if the values respects the defined constraints
func AssertSelectQueryConstraints(obj SelectQuery) error {
	return nil
}
