// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




// ShallowQuery - Description of a shallow representation of a query
type ShallowQuery struct {

	// ID of selected Query (I propose UUID, but it is under your own discretion)
	QueryId string `json:"queryId"`

	Status QueryStatus `json:"status"`
}

// AssertShallowQueryRequired checks if the required fields are not zero-ed
func AssertShallowQueryRequired(obj ShallowQuery) error {
	elements := map[string]interface{}{
		"queryId": obj.QueryId,
		"status": obj.Status,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertShallowQueryConstraints checks if the values respects the defined constraints
func AssertShallowQueryConstraints(obj ShallowQuery) error {
	return nil
}
