// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




// ExecuteQueryRequest - Used to submit a new query for execution
type ExecuteQueryRequest struct {

	QueryDefinition QueryQueryDefinition `json:"queryDefinition"`
}

// AssertExecuteQueryRequestRequired checks if the required fields are not zero-ed
func AssertExecuteQueryRequestRequired(obj ExecuteQueryRequest) error {
	elements := map[string]interface{}{
		"queryDefinition": obj.QueryDefinition,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertQueryQueryDefinitionRequired(obj.QueryDefinition); err != nil {
		return err
	}
	return nil
}

// AssertExecuteQueryRequestConstraints checks if the values respects the defined constraints
func AssertExecuteQueryRequestConstraints(obj ExecuteQueryRequest) error {
	if err := AssertQueryQueryDefinitionConstraints(obj.QueryDefinition); err != nil {
		return err
	}
	return nil
}
