// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




// Column - Description of single column in table
type Column struct {

	Name string `json:"name"`

	Type LogicalColumnType `json:"type"`
}

// AssertColumnRequired checks if the required fields are not zero-ed
func AssertColumnRequired(obj Column) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"type": obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertColumnConstraints checks if the values respects the defined constraints
func AssertColumnConstraints(obj Column) error {
	return nil
}
