// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




type QueryQueryDefinition struct {

	TableName string `json:"tableName,omitempty"`

	// Path to source CSV file (filepath in perspective of running server! NOT client)
	SourceFilepath string `json:"sourceFilepath"`

	DestinationTableName string `json:"destinationTableName"`

	// List of columns to copy data into. It creates a map from source columns to destination columns. Assumes that data in source file is in the same order as in this list.
	DestinationColumns []string `json:"destinationColumns,omitempty"`

	// Whether CSV file contains header row
	DoesCsvContainHeader bool `json:"doesCsvContainHeader,omitempty"`
}

// AssertQueryQueryDefinitionRequired checks if the required fields are not zero-ed
func AssertQueryQueryDefinitionRequired(obj QueryQueryDefinition) error {
	elements := map[string]interface{}{
		"sourceFilepath": obj.SourceFilepath,
		"destinationTableName": obj.DestinationTableName,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertQueryQueryDefinitionConstraints checks if the values respects the defined constraints
func AssertQueryQueryDefinitionConstraints(obj QueryQueryDefinition) error {
	return nil
}
