// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi


import (
	"fmt"
)


// LogicalColumnType : Enum describing logical column types
type LogicalColumnType string

// List of LogicalColumnType
const (
	INT64 LogicalColumnType = "INT64"
	VARCHAR LogicalColumnType = "VARCHAR"
)

// AllowedLogicalColumnTypeEnumValues is all the allowed values of LogicalColumnType enum
var AllowedLogicalColumnTypeEnumValues = []LogicalColumnType{
	"INT64",
	"VARCHAR",
}

// validLogicalColumnTypeEnumValue provides a map of LogicalColumnTypes for fast verification of use input
var validLogicalColumnTypeEnumValues = map[LogicalColumnType]struct{}{
	"INT64": {},
	"VARCHAR": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LogicalColumnType) IsValid() bool {
	_, ok := validLogicalColumnTypeEnumValues[v]
	return ok
}

// NewLogicalColumnTypeFromValue returns a pointer to a valid LogicalColumnType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLogicalColumnTypeFromValue(v string) (LogicalColumnType, error) {
	ev := LogicalColumnType(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for LogicalColumnType: valid values are %v", v, AllowedLogicalColumnTypeEnumValues)
}



// AssertLogicalColumnTypeRequired checks if the required fields are not zero-ed
func AssertLogicalColumnTypeRequired(obj LogicalColumnType) error {
	return nil
}

// AssertLogicalColumnTypeConstraints checks if the values respects the defined constraints
func AssertLogicalColumnTypeConstraints(obj LogicalColumnType) error {
	return nil
}
