// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




// SystemInformation - Basic information about the system
type SystemInformation struct {

	// Version of the DBMS interface
	InterfaceVersion string `json:"interfaceVersion,omitempty"`

	// Version of the DBMS system
	Version string `json:"version"`

	// Author of the DBMS system (will help me to automate testing)
	Author string `json:"author,omitempty"`

	// System uptime in seconds
	Uptime int64 `json:"uptime"`
}

// AssertSystemInformationRequired checks if the required fields are not zero-ed
func AssertSystemInformationRequired(obj SystemInformation) error {
	elements := map[string]interface{}{
		"version": obj.Version,
		"uptime": obj.Uptime,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSystemInformationConstraints checks if the values respects the defined constraints
func AssertSystemInformationConstraints(obj SystemInformation) error {
	return nil
}
