// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi




// MultipleProblemsError - Error containing multiple problems about request processing. Useful when processing complex requests where multiple problems can occur at the same time.
type MultipleProblemsError struct {

	Problems []MultipleProblemsErrorProblemsInner `json:"problems"`
}

// AssertMultipleProblemsErrorRequired checks if the required fields are not zero-ed
func AssertMultipleProblemsErrorRequired(obj MultipleProblemsError) error {
	elements := map[string]interface{}{
		"problems": obj.Problems,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Problems {
		if err := AssertMultipleProblemsErrorProblemsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertMultipleProblemsErrorConstraints checks if the values respects the defined constraints
func AssertMultipleProblemsErrorConstraints(obj MultipleProblemsError) error {
	for _, el := range obj.Problems {
		if err := AssertMultipleProblemsErrorProblemsInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
